-- MySQL Script generated by MySQL Workbench
-- 10/27/16 17:56:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema HI-TEC
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema HI-TEC
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HI-TEC` DEFAULT CHARACTER SET utf8 ;
USE `HI-TEC` ;

-- -----------------------------------------------------
-- Table `HI-TEC`.`EMPLOYEE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HI-TEC`.`EMPLOYEE` (
  `employee_id` INT NOT NULL,
  `employee_fname` VARCHAR(45) NOT NULL,
  `employee_lname` VARCHAR(45) NOT NULL,
  `employee_email` TEXT(50) NOT NULL,
  PRIMARY KEY (`employee_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HI-TEC`.`CATEGORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HI-TEC`.`CATEGORY` (
  `category_id` INT NOT NULL,
  `category_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HI-TEC`.`SECTION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HI-TEC`.`SECTION` (
  `section_id` INT NOT NULL,
  `section_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`section_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HI-TEC`.`AISLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HI-TEC`.`AISLE` (
  `aisle_id` INT NOT NULL,
  `aisle_number` INT NOT NULL,
  `section_id` INT NOT NULL,
  PRIMARY KEY (`aisle_id`),
  INDEX `aisle_fk_01_idx` (`section_id` ASC),
  CONSTRAINT `aisle_fk_01`
    FOREIGN KEY (`section_id`)
    REFERENCES `HI-TEC`.`SECTION` (`section_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HI-TEC`.`SHELF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HI-TEC`.`SHELF` (
  `shelf_id` INT NOT NULL,
  `shelf_number` INT NOT NULL,
  `aisle_id` INT NOT NULL,
  PRIMARY KEY (`shelf_id`),
  INDEX `shelf_fk_01_idx` (`aisle_id` ASC),
  CONSTRAINT `shelf_fk_01`
    FOREIGN KEY (`aisle_id`)
    REFERENCES `HI-TEC`.`AISLE` (`aisle_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HI-TEC`.`PERMISSION_GROUP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HI-TEC`.`PERMISSION_GROUP` (
  `permission_id` INT NOT NULL,
  `permission_group_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`permission_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HI-TEC`.`CLIENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HI-TEC`.`CLIENT` (
  `client_id` INT NOT NULL,
  `client_name` VARCHAR(45) NOT NULL,
  `client_contact` VARCHAR(45) NOT NULL,
  `client_email` TEXT(50) NOT NULL,
  PRIMARY KEY (`client_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HI-TEC`.`PHONE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HI-TEC`.`PHONE` (
  `phone_id` INT NOT NULL,
  `phone_number` TEXT(50) NOT NULL,
  PRIMARY KEY (`phone_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HI-TEC`.`CITY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HI-TEC`.`CITY` (
  `city_id` INT NOT NULL,
  `city_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`city_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HI-TEC`.`ADDRESS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HI-TEC`.`ADDRESS` (
  `address_id` INT NOT NULL,
  `address_street_number` VARCHAR(45) NOT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`address_id`),
  INDEX `address_fk_01_idx` (`city_id` ASC),
  CONSTRAINT `address_fk_01`
    FOREIGN KEY (`city_id`)
    REFERENCES `HI-TEC`.`CITY` (`city_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HI-TEC`.`MANUFACTURER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HI-TEC`.`MANUFACTURER` (
  `manufacturer_id` INT NOT NULL,
  `manufacturer_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`manufacturer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HI-TEC`.`SUPPLIER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HI-TEC`.`SUPPLIER` (
  `supplier_id` INT NOT NULL,
  `supplier_name` VARCHAR(45) NOT NULL,
  `supplier_contact` VARCHAR(45) NOT NULL,
  `address_id` INT NOT NULL,
  `phone_id` INT NOT NULL,
  `supplier_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`supplier_id`),
  INDEX `supplier_fk_01_idx` (`address_id` ASC),
  INDEX `supplier_fk_02_idx` (`phone_id` ASC),
  CONSTRAINT `supplier_fk_01`
    FOREIGN KEY (`address_id`)
    REFERENCES `HI-TEC`.`ADDRESS` (`address_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `supplier_fk_02`
    FOREIGN KEY (`phone_id`)
    REFERENCES `HI-TEC`.`PHONE` (`phone_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HI-TEC`.`PRODUCT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HI-TEC`.`PRODUCT` (
  `product_id` INT NOT NULL,
  `product_name` VARCHAR(45) NOT NULL,
  `product_price` DOUBLE NOT NULL,
  `supplier_id` INT NOT NULL,
  `manufacturer_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `shelf_id` INT NOT NULL,
  `product_img_path` TEXT(100) NOT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `product_fk_01_idx` (`supplier_id` ASC),
  INDEX `product_fk_02_idx` (`manufacturer_id` ASC),
  INDEX `product_fk_03_idx` (`category_id` ASC),
  INDEX `product_fk_04_idx` (`shelf_id` ASC),
  CONSTRAINT `product_fk_01`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `HI-TEC`.`SUPPLIER` (`supplier_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `product_fk_02`
    FOREIGN KEY (`manufacturer_id`)
    REFERENCES `HI-TEC`.`MANUFACTURER` (`manufacturer_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `product_fk_03`
    FOREIGN KEY (`category_id`)
    REFERENCES `HI-TEC`.`CATEGORY` (`category_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `product_fk_04`
    FOREIGN KEY (`shelf_id`)
    REFERENCES `HI-TEC`.`SHELF` (`shelf_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HI-TEC`.`EMPLOYEE_PHONE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HI-TEC`.`EMPLOYEE_PHONE` (
  `employee_id` INT NOT NULL,
  `phone_id` INT NOT NULL,
  PRIMARY KEY (`employee_id`, `phone_id`),
  INDEX `empPhone_fk_02_idx` (`phone_id` ASC),
  CONSTRAINT `empPhone_fk_01`
    FOREIGN KEY (`employee_id`)
    REFERENCES `HI-TEC`.`EMPLOYEE` (`employee_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `empPhone_fk_02`
    FOREIGN KEY (`phone_id`)
    REFERENCES `HI-TEC`.`PHONE` (`phone_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HI-TEC`.`EMPLOYEE_CREDS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HI-TEC`.`EMPLOYEE_CREDS` (
  `employee_id` INT NOT NULL,
  `employee_password` VARCHAR(45) NOT NULL,
  `permission_id` INT NOT NULL,
  PRIMARY KEY (`employee_id`),
  INDEX `empCred_fk_02_idx` (`permission_id` ASC),
  CONSTRAINT `empCred_fk_01`
    FOREIGN KEY (`employee_id`)
    REFERENCES `HI-TEC`.`EMPLOYEE` (`employee_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `empCred_fk_02`
    FOREIGN KEY (`permission_id`)
    REFERENCES `HI-TEC`.`PERMISSION_GROUP` (`permission_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HI-TEC`.`LOCATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HI-TEC`.`LOCATION` (
  `location_id` INT NOT NULL,
  `location_name` VARCHAR(45) NOT NULL,
  `client_id` INT NOT NULL,
  `contact_name` VARCHAR(45) NOT NULL,
  `address_id` INT NOT NULL,
  `phone_id` INT NOT NULL,
  PRIMARY KEY (`location_id`),
  INDEX `location_fk_01_idx` (`client_id` ASC),
  INDEX `location_fk_02_idx` (`address_id` ASC),
  INDEX `location_fk_03_idx` (`phone_id` ASC),
  CONSTRAINT `location_fk_01`
    FOREIGN KEY (`client_id`)
    REFERENCES `HI-TEC`.`CLIENT` (`client_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `location_fk_02`
    FOREIGN KEY (`address_id`)
    REFERENCES `HI-TEC`.`ADDRESS` (`address_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `location_fk_03`
    FOREIGN KEY (`phone_id`)
    REFERENCES `HI-TEC`.`PHONE` (`phone_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HI-TEC`.`CLIENT_LOCATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HI-TEC`.`CLIENT_LOCATION` (
  `client_id` INT NOT NULL,
  `location_id` INT NOT NULL,
  PRIMARY KEY (`client_id`, `location_id`),
  INDEX `clientLoc_fk_02_idx` (`location_id` ASC),
  CONSTRAINT `clientLoc_fk_01`
    FOREIGN KEY (`client_id`)
    REFERENCES `HI-TEC`.`CLIENT` (`client_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `clientLoc_fk_02`
    FOREIGN KEY (`location_id`)
    REFERENCES `HI-TEC`.`LOCATION` (`location_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HI-TEC`.`ORDER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HI-TEC`.`ORDER` (
  `order_id` INT NOT NULL,
  `supplier_id` INT NOT NULL,
  `order_date` DATE NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `order_fk_01_idx` (`supplier_id` ASC),
  CONSTRAINT `order_fk_01`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `HI-TEC`.`SUPPLIER` (`supplier_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HI-TEC`.`ORDER_PRODUCT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HI-TEC`.`ORDER_PRODUCT` (
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`order_id`, `product_id`),
  INDEX `orderProduct_fk_02_idx` (`product_id` ASC),
  CONSTRAINT `orderProduct_fk_01`
    FOREIGN KEY (`order_id`)
    REFERENCES `HI-TEC`.`ORDER` (`order_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `orderProduct_fk_02`
    FOREIGN KEY (`product_id`)
    REFERENCES `HI-TEC`.`PRODUCT` (`product_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HI-TEC`.`SHIPMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HI-TEC`.`SHIPMENT` (
  `shipment_id` INT NOT NULL,
  `location_id` INT NOT NULL,
  `shipment_date` DATE NOT NULL,
  `hasShipped` TINYINT(1) NOT NULL,
  PRIMARY KEY (`shipment_id`),
  INDEX `shipment_fk_01_idx` (`location_id` ASC),
  CONSTRAINT `shipment_fk_01`
    FOREIGN KEY (`location_id`)
    REFERENCES `HI-TEC`.`LOCATION` (`location_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HI-TEC`.`SHIPMENT_PRODUCT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HI-TEC`.`SHIPMENT_PRODUCT` (
  `shipment_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`shipment_id`, `product_id`),
  INDEX `shipProduct_fk_02_idx` (`product_id` ASC),
  CONSTRAINT `shipProduct_fk_01`
    FOREIGN KEY (`shipment_id`)
    REFERENCES `HI-TEC`.`SHIPMENT` (`shipment_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `shipProduct_fk_02`
    FOREIGN KEY (`product_id`)
    REFERENCES `HI-TEC`.`PRODUCT` (`product_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
