insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (1, 28, '12', 'Grover', 'massa', 3);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (2, 6, '016', 'Cordelia', 'viverra', 5);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (3, 26, '34', 'Annamark', 'pulvinar', 3);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (4, 12, '87664', 'Westridge', 'eget', 12);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (5, 24, '8988', 'Atwood', 'diam', 8);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (6, 17, '46315', 'Banding', 'non', 10);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (7, 10, '26', 'Tomscot', 'sit', 17);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (8, 8, '0', '1st', 'sed', 10);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (9, 25, '34', 'Reinke', 'in', 14);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (10, 18, '5', 'Dapin', 'nisi', 16);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (11, 22, '0', 'Warrior', 'lacinia', 16);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (12, 6, '617', 'Gale', 'a', 13);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (13, 21, '3', 'Alpine', 'erat', 16);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (14, 2, '32', 'Brickson Park', 'maecenas', 3);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (15, 2, '335', 'Porter', 'erat', 1);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (16, 3, '5', 'Shelley', 'elementum', 5);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (17, 8, '8428', 'Schurz', 'libero', 17);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (18, 17, '405', 'Melody', 'velit', 11);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (19, 7, '4', 'Grayhawk', 'dolor', 14);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (20, 20, '1826', 'Forest Dale', 'vivamus', 5);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (21, 4, '8435', 'Macpherson', 'diam', 11);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (22, 20, '89596', 'Vidon', 'tellus', 17);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (23, 5, '97518', 'Grayhawk', 'in', 6);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (24, 12, '652', 'Muir', 'id', 18);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (25, 5, '3378', 'Mallory', 'at', 6);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (26, 16, '897', 'Wayridge', 'lorem', 1);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (27, 28, '67565', 'Little Fleur', 'nec', 4);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (28, 22, '8762', 'Marquette', 'duis', 10);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (29, 14, '8271', 'Pine View', 'varius', 12);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (30, 5, '003', 'Moulton', 'euismod', 13);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (31, 26, '864', '7th', 'interdum', 18);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (32, 22, '84', 'Algoma', 'molestie', 8);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (33, 18, '1', 'Loeprich', 'faucibus', 1);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (34, 19, '408', 'Milwaukee', 'eu', 9);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (35, 17, '514', 'Farragut', 'nec', 3);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (36, 11, '454', 'Gateway', 'rutrum', 3);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (37, 27, '4310', 'Iowa', 'nec', 1);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (38, 14, '08', 'Delaware', 'lacinia', 7);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (39, 21, '05', 'Dennis', 'ultrices', 4);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (40, 8, '71021', 'Dunning', 'turpis', 13);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (41, 3, '5843', 'Kropf', 'orci', 4);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (42, 6, '8', 'Sage', 'vel', 17);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (43, 27, '165', 'David', 'semper', 13);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (44, 17, '1508', 'Hayes', 'quis', 10);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (45, 22, '4', 'Annamark', 'ipsum', 18);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (46, 20, '06608', 'Twin Pines', 'massa', 5);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (47, 18, '61', 'Cordelia', 'id', 9);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (48, 23, '7', 'Northfield', 'varius', 11);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (49, 11, '03272', 'Cottonwood', 'posuere', 9);
insert into address (address_id, address_unit_number, address_street_number, address_street_name, address_postcode, city_id) values (50, 26, '9', 'Daystar', 'dolor', 12);
